## https://pnpm.io/pnpm-workspace_yaml
## https://pnpm.io/settings

## https://pnpm.io/workspaces
packages:
  - A-meta/*
  - B-packages/*
  - C-apps/*
autoInstallPeers: false

catalog:
  '@anthropic-ai/claude-agent-sdk': ^0.2.87
  "@types/node": '^25'
  "@types/react": '^19'
  "@types/react-dom": '^19'
  "@vitejs/plugin-react": "^6"
  "globals": "*"
  react: '^19'
  react-dom: '^19'
  "typescript": "~6"
  vite: '^8'
catalogMode: prefer

hoist: false
strictPeerDependencies: true
